language: java
jdk: openjdk17
script: 
  # Install latest version of Maven compatible with JDK 17. Use archives for permalink to fixed version
  - wget https://archive.apache.org/dist/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz -P /tmp
  - sudo tar xf /tmp/apache-maven-*.tar.gz -C /usr/local/bin/
  - export M2_HOME=/usr/local/bin/apache-maven-3.8.5
  - export PATH=${M2_HOME}/bin:${PATH}
  - mvn package
cache:
  directories:
    - "$HOME/.m2"
branches:
  only:
    - "/^(feature|bugfix)\\/(SCC|SCAT|CON)-[0-9]+.*$/"
    - "/^(release)\\/.*$/"
    - "/^snyk-(upgrade|fix)-[a-z0-9]+$/"
    - develop
    - main

# Install dependencies
before_install:
  - sudo rm -Rf terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo rm -Rf terraform
  - wget https://releases.hashicorp.com/terraform/"$TF_VERSION"/terraform_"$TF_VERSION"_linux_amd64.zip
  - unzip terraform_"$TF_VERSION"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$TF_VERSION"_linux_amd64.zip

deploy:
  # SBX - modify CF_ENVIRONMENT as required
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=sbx2 bash ./deploy.sh
    on:
      all_branches: true
      condition: "${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^(feature|bugfix)\\/(SCC|SCAT|CON)-[0-9]+.*$ || ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} =~ ^snyk-(upgrade|fix)-[a-z0-9]+$"

  # DEVELOP
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=dev bash ./deploy.sh
    on:
      branch: develop

  # INT (SIT)
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=int bash ./deploy.sh
    on:
      branch: release/int

  # NFT
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=nft bash ./deploy.sh
    on:
      branch: release/nft

  # UAT
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=uat bash ./deploy.sh
    on:
      branch: release/uat

  # PRE
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=pre bash ./deploy.sh
    on:
      branch: release/pre      

  # PRD
  - provider: script
    skip_cleanup: true
    script: CF_ENVIRONMENT=prd bash ./deploy.sh
    on:
      branch: release/prd      

# WARNING! Do NOT use the --add flag of travis cli encrypt - it removes all formatting and comments
env:
  global:
    # ACCESS_KEY_ID
    - secure: "XL2rQZLdro/UYjxTRifjIrS++CItEVQ6IAK5cP8FhLA82o7Vyju2yL4bzIXoojZ1iuAURb67rIimeHQVZp70tlwK5gYr1E0S4IOeBi5a483cdYxvBxp3WjHsK5dZJfyc0+czo+aAuiLH1FTOMEV/jUCxhxpe36IV5jci71dnKDxv/T0/VfiBwH3Ubi5Whb4SfVY6MgILF5xcnqtok3z/VzKQnBTrv8KQD6N5mDlueEUNvWZOg/wrXqu5TauRhJPQxlZx00y5cKE1/5YJu8v9LP6aEOaFRwUVLuhbDQ9cvdVcUIXzLVWP7EHg/4/q6MqNS17ym8k3RjVRYBzG8p6kHPjnunYPFcb5ZwtfLbn+wAHjmTEI3PuHngUIBgeQBX+e7cEMPnrh/V2fr9j1jreEca0uAmRpR1oq24P6uL3MKyFsr6H039wW1jOPShHCVhecPDAvOviTiIwISVSGFvj6pjsvFhSLKChWU6gs86EJccRkiytq6vPrhWe6DqLJN6rt5nftOqYIKRxfoxuBAfQNhzOUjy2AWcrnL8xGnySDzGOEFKbYghFOqc1SJJ/nHZ/TtuKQcm6Ch76U7mGQrq+x2u+06bgmLk4Zka2nSgZPHcsh2ynM5VvMLcqkzXm1Qq89jgy8xYBBBU9OftMUaiuJQihYOEvry0I70Vhb2Mk5sO0="
    # SECRET_ACCESS_KEY
    - secure: "Bqtr3TXSH5xq1z4lDOaX77iglazpcY0WdaUR4BfIFyyohApky5+UdnDN9ewxgL/DVBWrhxS4BjjyhBm6gK3eAdzfH9q9eYSPb2Cg+J2gY2xTwM8/HwMkwlbH4Zb1j4kmKkDJ9yEAis2BgLa5aSeAE6K3mTEO/QCA6kLTXzKcHgGiO5nn8w+XGu9HAJ09ap/RL4ZPc5tqrMyTMB3N1oAkVYehj+0cmf678EzVUoqPLqUF/N6ScBvjrpQZdL1ZfyyR0EXbbqsozikY/Sdjb0zgw1iXFxNyLwlLDC6bcFof1bY0OG/n9g+nvAjkHMlLvkkGuEU9GYDrKXCw4SENeZ7nVA7FvVbBIFodWfhYpBnj9mdW27xV5EhiaqmE1B25zJiehY9Unu/iaKfjzIIz2GsqJcefDubPJb8ZEgbrG1bqhIG+aPFWtm2JfSUcqHnsOScQvmFFW4us9dPX5Xlsm2dT1qFUuXYjyjHmcbwGi9Bgl2pSKk3eLa9gHRvvmyYJiZsD2gj2b9lAubD+EoVp/d/4whRTKN1h6aBNPJbsDeZW9ao9SaIcvtAqeezT4DBy+thKbQNDU1uPKMLQD7z/9pyi2LsK9JayXPjErlbckf1irIDRUBC0UDstpMvz/ikXcVWjKhvZ1ivALzsREn2DCPLgDOHyTKOrseSRHU1oGladyS8="
    # S3_STATE_BUCKET_NAME
    - secure: "FbOlT9fo8E6nIdWIjLo7/nuwx340DH2YXO3hZF0+KdxEDcZC5V/KAF1x86qGcLkOlfaxbpqI4nQdWh/ATJRyZe3EU0HiOtTSGnOHdmpDdciHJaQyleoOAdkOcywyTOsPcRgO07NwgnncTY0JFGXI/A0alUxLSApSc0og09SHYK3mjP3uQaOjCQngZf3N55J/EzMQDpk7Fmr/QSx77eZn+m/90ZAT+xRus2JFNbxg56Uaj6e0KC60wgsctUI8KIVP/uKXO8t1q+3j1pBCGGCivR/Yd/a7YP1csj9Z0zKs1/DbB60OxOwr5ZcKAf9m8JN+E76ykW11CmHzQrwjnlFN5gGpJUkAM/AKPzaSP8vQoi7JmTdKSIysQzT7y3dsSMp0QhU5turna4AQ7kqSNCwQl5AQWuZqWw3HiU3cOby98+CMmfY1imCwxV888ByRvXIqzx+O4sS4G9F8tUjvhdddYMoB9PeY7OBYEwP5/on/w98s6JXFPrkdKRHJFub8zjSMYxwpbuYu/EJZWIeNzrqGCx18JF96+64Nj8YNsBwIo0PJ57dB9LajVKTgdwnbEEu7Zkk6xKQSCVIUUUwsT2eO34jVFACbGVR7mEDUioptVFXt8wmvX3ftOG39JQHypRy8uunpYk1G1U6qewYbIMiRrYdwNfvyBcVbeihbhh0SuJQ="
    # DDB_LOCK_TABLE_NAME
    - secure: "WfuCos2MaZwFiK+KDUFEkrmxeEJlAvr/KJ0jVv+4HBlWZtiNNeWB+0tbwpUfx/icjNSlW/wvk+FrFEJN6JhUlKXwvjNbLe6CRiBHk8LIhg9DizdPq80pVn5Qn9dAzQCKIn7/sD0uzhOK++LcBjaZPWHBsA6vV+HpBGBFrghPj6Jqe001dm/5fMs9iNCJmPvZyFFNSIh+GxapTyS19onNlLwD7ptuNOd9zMp8ArD0PAD2zOfbqk6FIp5j7Nc3OXa4+mbqW7fCMTOmLHdeli8mL0doo8bJXtv9uwmAb5aefOFBFk3SY/efjoZhCjn+cz24uNnM2pIe5lwFuUvZ0UmcZWp6J7vlPu4JVtto6vpSO7dvMYc1112z75MfksR8THXd5bbHwEEes8SV//X+CdDLJTd60UUqdIAy8kQuDGuGc1U8BF6wC+sSC7wqAqFk/oMOM03gK2XzBj5jQmeXW3fxnzfWoMS2wJNkhWFiF7k9+JIc/E4Y/81+OeJMS+7dMD0l1yQBAceaQPmbEUnrRpLsmfD2K8efjh7xGM2crGNpst/6w40aznDwc3brr+TYU5Z4HTzh09KZBfn+JJRqtxClqZLduLdn7JwUox9bi11ax3v4nQRQUpkB02LJL1+9wMD7ArkO7P8YNvoJb3iI1OgOI9P3EewtgCu/XkyOeYta5j4="
    # CF_USERNAME
    - secure: "OHs3wKC2q3XwGsO8Skqgk4SV4upXltiMPiAIHhTbMqOjSnPa2siOjmrFrkyZwT5gYe4YcENB9amV30GIgSpCkzzNbOPVTMF7tafK+8hXIrlvQuOXMx00zq2ry/XD/lQrxNBZFZlxOxV9mUlJ3bBCHnNwe8oEO6kAZxwmS8QXBhHvM1KKVL4LT/k9MFJQ/DbZEmFHyQByig9TkooTjUNYWgmPxRbP/6Yofkg/kNDUerhwU+PLStIKd61bJBwZbFTEy3hYWdwvjrox3RIhdzsFPREn1pJkNRcgEGQiULGcmpplPe3iAlMp9C48HgiPyK00MTvpiSlRSpO/fJMOFyyq/zn0oxS4f/MbfJ/9x0XQFFyJkns3ioHG6BlGV7A0GOOnvGclov9a3P/423hTvllwuN9sYv0iqpljVJUeJ3wsBhp+ALFZqkMhUltlkGH+ENH5fvtED/u4D5YA1lfogTJOc4C4qBDFC61QAWhyXoiVEaXcKvpSDYLqZUe6HDbFpY7DPIO4HoRiZw+xUaWkmxeymsCU8mQmFMQg6KwUmYXggP+BwGlaaWbbXwffG2yIl2K/JVhshWrzdHfy5wSBREPonkO50X7RROWYJd01zOhggLRybVWsGQyASNunzYAYVrWPoA48NSiCG5iTQrUMxMTzVfIPvRR0aL6eXCB6dbLSzFE="
    # CF_PASSWORD
    - secure: "g8KwewOWAx6KFlQbCYcTHVnQu3UhHjcMxEdxUO8Y/hlHyjvXNrYsVkvc6JXnS4aNER6otOs9+cl2DOGtAiwUTpHyR/kYgk+I/FaOCf7pEMSUIIw8JL6SckH4hqAZcR/z49IABvN1YRSPI7x4mW6OVxRQ/6eKGJByhj/dM1dZ2AMQ45+SbriXu6+8/iP/i2fjsSY6WZXROvf8foBkeRW59D8YVn9ZIaHP2JwN+EE2hUJukbakO0xrqO2lptDpkEs7L3FwwwcQ2mSQxF9N7puGqCvKSr+Lx/Fr4aQAU6+xrhn3eQ3svcP5eVr0tMZmDiV5y7neNXfInRvnj9x5W8QwN9frT2axqGE/MK8cJqfpLp6Q6hQ3NL19eOIVaWI6e3F3B70IPn16GqSEqkogwZvpCYWfPmwhW8f/2JdYc1jBACeCfYUJSHD1/qUikN8beQI2ImMJSVQZW/Su8grok6SjU8VAl/ICIibneMPvJ+CbyRx+hSBt2Z3x7A1XwLsMzYBkbK0m9ymAVemYL+A2xz6Y9Zyy7Agj/R/ZHM3sbGLig+eLviG/+7qY081zRtUtO4KsZKte1QpjkrsgTFoiCQIG4nkrd2KRdx8FhopUE9BbgNjk8VJMRVfJkEjgXLgNw2G6qWat+9RTH7xCCOdkx6FjZqU5Qz6RnitUEpKVcesIxDc="
    - TF_VERSION=1.0.5
